import Base from "../../component/Base";
var ModelEvent = {};
ModelEvent.PlayByUi = "ModelEvent.PlayByUi";
ModelEvent.PauseByUi = "ModelEvent.PauseByUi";
ModelEvent.FullScreenByUi = "ModelEvent.FullScreenByUi";
ModelEvent.NormalScreenByUi = "ModelEvent.NormalScreenByUi";
ModelEvent.OpenDanmakuByUi = "ModelEvent.OpenDanmakuByUi";
ModelEvent.CloseDanmakuByUi = "ModelEvent.CloseDanmakuByUi";
ModelEvent.ChangeVolumeByUi = "ModelEvent.ChangeVolumeByUi";
export default ModelEvent;
